<a href="https://colab.research.google.com/github/thetmon4/SML_Teaching/blob/main/life_expectency.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

In [38]:
# Replace 'your_file.xlsx' with the actual path to your Excel file
df= pd.read_csv('life_expectancy.csv')

# New Section

In [39]:
X = df[['Prevelance of Undernourishment', 'Health Expenditure %', 'Education Expenditure %']]
y = df['Life Expectancy World Bank']
df

,Country Name,Country Code,Region,IncomeGroup,Year,Life Expectancy World Bank,Prevelance of Undernourishment,CO2,Health Expenditure %,Education Expenditure %,Unemployment,Corruption,Sanitation,Injuries,Communicable,NonCommunicable
0,Afghanistan,AFG,South Asia,Low income,2001,56.308,47.8,730.000000,NaN,NaN,10.809000,NaN,NaN,2179727.10,9689193.70,5795426.38
1,Angola,AGO,Sub-Saharan Africa,Lower middle income,2001,47.059,67.5,15960.000000,4.483516,NaN,4.004000,NaN,NaN,1392080.71,11190210.53,2663516.34
2,Albania,ALB,Europe & Central Asia,Upper middle income,2001,74.288,4.9,3230.000000,7.139524,3.45870,18.575001,NaN,40.520895,117081.67,140894.78,532324.75
3,Andorra,AND,Europe & Central Asia,High income,2001,NaN,NaN,520.000000,5.865939,NaN,NaN,NaN,21.788660,1697.99,695.56,13636.64
4,United Arab Emirates,ARE,Middle East & North Africa,High income,2001,74.544,2.8,97200.000000,2.484370,NaN,2.493000,NaN,NaN,144678.14,65271.91,481740.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3301,Vanuatu,VUT,East Asia & Pacific,Lower middle income,2019,70.474,12.4,209.999993,3.360347,1.77788,1.801000,3.0,NaN,12484.18,26032.56,69213.56
3302,Samoa,WSM,East Asia & Pacific,Lower middle income,2019,73.321,4.4,300.000012,6.363094,4.70625,8.406000,4.0,47.698788,6652.84,9095.19,43798.62
3303,South Africa,ZAF,Sub-Saharan Africa,Upper middle income,2019,64.131,6.3,439640.014648,9.109355,5.91771,28.469999,NaN,NaN,3174676.10,13198944.71,10214261.89
3304,Zambia,ZMB,Sub-Saharan Africa,Low income,2019,63.886,NaN,6800.000191,5.312203,4.46518,12.520000,2.5,NaN,510982.75,4837094.00,2649687.82
3305,Zimbabwe,ZWE,Sub-Saharan Africa,Lower middle income,2019,61.490,NaN,11760.000229,7.703565,NaN,4.833000,2.5,25.963544,644798.93,4187087.31,2364031.48

In [50]:
df['Life Expectancy World Bank'].value_counts()

80.702439    192
82.204878      3
74.904000      3
80.746341      3
75.400000      3
            ...
54.842000      1
69.372683      1
70.409000      1
77.227000      1
61.490000      1
Name: Life Expectancy World Bank, Length: 2966, dtype: int64

In [51]:
df = pd.DataFrame(df)

# Separate the numeric and non-numeric values
numeric_values = df['Life Expectancy World Bank'].loc[pd.to_numeric(df['Life Expectancy World Bank'], errors='coerce').notna()]
non_numeric_values = df['Life Expectancy World Bank'].loc[pd.to_numeric(df['Life Expectancy World Bank'], errors='coerce').isna()]

# Calculate the most frequent numeric value
most_frequent_numeric = numeric_values.mode().iloc[0]

# Replace missing numeric values with the most frequent numeric value
df['Life Expectancy World Bank'] = pd.to_numeric(df['Life Expectancy World Bank'], errors='coerce').fillna(most_frequent_numeric)

# Replace missing non-numeric values with a default value (e.g., 'Unknown')
df['Life Expectancy World Bank'].fillna('Unknown', inplace=True)

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 42)

In [57]:
imputer = SimpleImputer(strategy='most_frequent')
df['Life Expectancy World Bank'] = imputer.fit_transform(df[['Life Expectancy World Bank']])

In [58]:
# Split the data into training and testing sets
steps = [("imp_mean", SimpleImputer()), # cleaning the data - replace the missing data with average
            ("scale", StandardScaler()),  #standardizing the data
            ("linear", LinearRegression()) ] # linear model - ML


pipeline = Pipeline(steps)

model = pipeline.fit(X_train,y_train)

ValueError: ignored

In [59]:
X = df.values
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.4, random_state = 42)

model, a, b = my_linear_regression(X_train,y_train)
y_pred = model.predict(X_train)

mae = mean_absolute_error(y_train, y_pred)
mse = mean_squared_error(y_train, y_pred)
r2 = r2_score(y_train,y_pred)
print('training')
print('mae:', round(mae), 'mse:', round(mse), 'r2 score:', round(r2, 2))

y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test,y_pred)
print('testing')
print('mae:', round(mae), 'mse:', round(mse), 'r2 score:', round(r2, 2))

NameError: ignored